version: '3'
services: 
  bot:
    container_name: stoic_jackson
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - config.env
    volumes:
      - ./logger.log:/app/logger.log
    command: python bot.py
